apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ocp-enmasse-app
    name: ocp-enmasse-app
    namespace: enmasse-infra
  spec:
    ports:    
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    selector:
      app: ocp-enmasse-app
      deploymentconfig: ocp-enmasse-app
    type: LoadBalancer
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ocp-enmasse-app
    name: ocp-enmasse-app
    namespace: enmasse-infra
  spec:
    to:
      kind: Service
      name: ocp-enmasse-app
      weight: 100
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ocp-enmasse-app
    name: ocp-enmasse-app
    namespace: enmasse-infra
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ocp-enmasse-app
        deploymentconfig: ocp-enmasse-app
    template:
      metadata:
        labels:
          app: ocp-enmasse-app
          deploymentconfig: ocp-enmasse-app
      spec:
        containers:
        - image: famargon/ocp-enmasse-app
          imagePullPolicy: Always
          name: ocp-enmasse-app
        terminationGracePeriodSeconds: 30
