apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: systemtests-cert-validator
    name: systemtests-cert-validator
    namespace: enmasse-infra
  spec:
    ports:    
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
    selector:
      app: systemtests-cert-validator
      deploymentconfig: systemtests-cert-validator
    type: LoadBalancer
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: systemtests-cert-validator
    name: systemtests-cert-validator
    namespace: enmasse-infra
  spec:
    to:
      kind: Service
      name: systemtests-cert-validator
      weight: 100
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: systemtests-cert-validator
    name: systemtests-cert-validator
    namespace: enmasse-infra
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: systemtests-cert-validator
        deploymentconfig: systemtests-cert-validator
    template:
      metadata:
        labels:
          app: systemtests-cert-validator
          deploymentconfig: systemtests-cert-validator
      spec:
        containers:
        - image: enmasse/systemtests-cert-validator
          imagePullPolicy: Always
          name: systemtests-cert-validator
        terminationGracePeriodSeconds: 30
